version: "2"

volumes:
  postgres-data:
    driver: local
  gems:
    driver: local

services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data # The postgres data volume
      - ./db/dumps:/db/dumps                   # The dumps folder so we can backup and restore data dumps quickly
      - ./bin/restoredb:/bin/restoredb:ro      # The 'restoredb' script
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: P4Ssw0rD!

  test:
    image: ccz/ccz_webpage:development
    command: rspec spec/
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /code
    volumes:
      - .:/code
      - gems:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
      DATABASE_URL: "postgres://postgres:P4Ssw0rD!@db:5432/ccz_webpage_test"
      RACK_ENV: "test"
      RAILS_ENV: "test"
      LC_ALL: C.UTF-8
    links:
      - db

  web: &app
    image: ccz/ccz_webpage:development
    command: rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /code
    volumes:
      - .:/code
      - gems:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
      DATABASE_URL: "postgres://postgres:P4Ssw0rD!@db:5432/ccz_webpage"
      LC_ALL: C.UTF-8
    links:
      - db

